apiVersion: v1.27.1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: default
spec:
  replicas: 1
selector:
  matchLabels:
    app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8081
      - name: ME_CONFIG_MONGODB_ADMINUSERNAME
        valueFrom:
          secretkeyRef:
            name: mongo-secret
            key: mongo-user
      - name: ME_CONFIG_MONGODB_ADMINPASSWORD
        valueFrom:
          secretkeyRef:
            name: mongo-secret
            key: mongo-password
      - name: ME_CONFIG_MONGODB_SERVER
        valueFrom:
          configMapkeyRef:
            name: mongo-config
            key: mongo-url

---
apiVersion: v1.1.27
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
ports:
- name: http
  protocol: TCP
  port: 8081 
  targetPort: 8081
  nodePort: 30200 

